mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('comments/', views.comment_view, name='comments'),
    path('comments/list/', views.CommentView.comment_list_view, name='commentlist'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import  timezone
from django.contrib import admin
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )

    def was_published_recently(self):
        now=timezone.now()
        return now-datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question=models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Comment(models.Model):
    title_text = models.CharField(max_length=200)
    comment_text = models.CharField(max_length=200)

polls/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['title', 'text']

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.template import loader
from django.utils import timezone
from .models import Choice, Question, Comment
from django.views import generic

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]
class CommentView(generic.ListView):
    model=Comment
    template_name = 'polls/comment.html'
    
    def comment_list_view(request):
        comments = Comment.objects.all()
        context = {'comments': comments}
        return render(request, 'polls/comment.html', context)

class CommentPostView(generic.DetailView):
    model=Comment
    template_name = 'polls/postcom.html'
    

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_commentset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404r(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})

def get_queryset(self):
    return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

def comment(request):
    latest_comment_list = Comment.object.order_by('-pub_date')[:5]
    context = {'latest_comment_list': latest_comment_list}
    return render(request, 'polls/comment.html', context)

def comment_view(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        text = request.POST.get('text')
        comment = Comment(title_text=title,comment_text=text)
        comment.save()
    return render(request, 'polls/postcom.html')

polls/templates/polls/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Comment Posted</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <div class="container">
      <a class="navbar-brand fw-semibold" href="{% url 'polls:comments'%}">
        <img src="https://previews.dropbox.com/p/thumb/AB2fKOVRrqQIAX3Ws7PwgOFgZUxqcvJARlrGssT7geSR_n9Q5IUNFmP-QBBqLejuyNMihp6jEuboA0GMhLQj1S6EJxHLPmdFFtqDEPwmrnhB0JrdvURhHlvkppkTOSCHbRHS44C7ANIW-6ogzmG4oiubIxjhUVGGmJtwfhRipAYdRJL9tJgQZaEfw9xrhzgqUdni_TdLmHrLZMwSuXDNsvy_HoAUVMcCYH8kQw2l9KOTuVelejFmWy8qzXl4_ijHjR4HRdx11P49yCIFUITV79nKrV5VQX7aSberR2xr-omSYZoORMe4tK27Ghjk0gl6bah6Hw6GKX4C2vT-YR6PJ3Cvakwgq_N_kV76gk8E3R6PIXQB6t1tCIYoU9U7aYpexOg/p.png" style="width: 50px; height:55px;" class="image-responsive me-3">
        MoFololo
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:index'%}">Polls</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:comments'%}">Comment</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:commentlist'%}">List</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container-fluid m-3 p-3">
    {% for comment in comments %}
      <div class="container m-3 p-2" style="border: 5px solid #e59a0e; border-radius: 5px;">
        <div class="row">
          <div class="col-4">
            <h3 class="text-center">{{ comment.title_text }}</h3>
          </div>
          <div class="col-8">
            <p class="text-justify">{{ comment.comment_text }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  
  <footer class="bg-warning text-white p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2023 David</p>
        </div>
        <div class="col-md-6">
          <ul class="list-inline text-md-end">
            <p>Published Date: Feb, 16, 2023
            <p>Author: David Da Lian</p>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Comment Posted</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
        <div class="container">
          <a class="navbar-brand fw-semibold" href="{% url 'polls:comments'%}">
            <img src="https://previews.dropbox.com/p/thumb/AB2fKOVRrqQIAX3Ws7PwgOFgZUxqcvJARlrGssT7geSR_n9Q5IUNFmP-QBBqLejuyNMihp6jEuboA0GMhLQj1S6EJxHLPmdFFtqDEPwmrnhB0JrdvURhHlvkppkTOSCHbRHS44C7ANIW-6ogzmG4oiubIxjhUVGGmJtwfhRipAYdRJL9tJgQZaEfw9xrhzgqUdni_TdLmHrLZMwSuXDNsvy_HoAUVMcCYH8kQw2l9KOTuVelejFmWy8qzXl4_ijHjR4HRdx11P49yCIFUITV79nKrV5VQX7aSberR2xr-omSYZoORMe4tK27Ghjk0gl6bah6Hw6GKX4C2vT-YR6PJ3Cvakwgq_N_kV76gk8E3R6PIXQB6t1tCIYoU9U7aYpexOg/p.png" style="width: 50px; height:55px;" class="image-responsive me-3">
            MoFololo
          </a>
    
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
            <span class="navbar-toggler-icon"></span>
          </button>
    
          <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:index'%}">Polls</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:comments'%}">Comment</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:commentlist'%}">List</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      
<div class="container-sm bg-warning my-4 p-1 text-start" style="border:4px groove #071797;border-radius: 5px;">
    <h4 class="fw-bold m-2" >Question {{question.id}}</h4>
    <form class="bg-white m-2 p-2" style="border-radius:5px"action="{% url 'polls:vote' question.id %}" method="post">
        {%csrf_token%}
        <p class="fw-bold text-start px-3" >{{question.question_text}}</p>
        {% for choice in question.choice_set.all %}
            <div class="form-check mb-2 px-5">
                <input class="form-check-input" type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
                <label class="form-check-label" for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
            </div>
        {% endfor %}
        <div class="text-end mx-3 px-3">
        <button class="btn btn-primary"  type="submit"  value="vote">Submit</button>
        </div>
    </form>
</div>

<footer class="bg-warning text-white p-3 fixed-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2023 David</p>
        </div>
        <div class="col-md-6">
          <ul class="list-inline text-md-end">
            <p>Published Date: Feb, 16, 2023
            <p>Author: David Da Lian</p>
          </ul>
        </div>
      </div>
    </div>
  </footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

polls/templates/polls/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Questions</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    {% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <div class="container">
      <a class="navbar-brand fw-semibold" href="{% url 'polls:comments'%}">
        <img src="https://previews.dropbox.com/p/thumb/AB2fKOVRrqQIAX3Ws7PwgOFgZUxqcvJARlrGssT7geSR_n9Q5IUNFmP-QBBqLejuyNMihp6jEuboA0GMhLQj1S6EJxHLPmdFFtqDEPwmrnhB0JrdvURhHlvkppkTOSCHbRHS44C7ANIW-6ogzmG4oiubIxjhUVGGmJtwfhRipAYdRJL9tJgQZaEfw9xrhzgqUdni_TdLmHrLZMwSuXDNsvy_HoAUVMcCYH8kQw2l9KOTuVelejFmWy8qzXl4_ijHjR4HRdx11P49yCIFUITV79nKrV5VQX7aSberR2xr-omSYZoORMe4tK27Ghjk0gl6bah6Hw6GKX4C2vT-YR6PJ3Cvakwgq_N_kV76gk8E3R6PIXQB6t1tCIYoU9U7aYpexOg/p.png" style="width: 50px; height:55px;" class="image-responsive me-3">
        MoFololo
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:index'%}">Polls</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:comments'%}">Comment</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:commentlist'%}">List</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<div class="container-fluid mt-3 mb-5 ms-3 me-3 p-3">
    <h1 class="fw-bold m-3 p-3 text-center"> Question List</h1>
{% if latest_question_list %}
    {% for question in latest_question_list %}
        <div class="bg-warning col-8 mx-3 my-4 px-5 py-3 rounded-pill border border-5 mx-auto">
            <a href="/polls/{{ question.id }}/" >{{ question.question_text }}</a>
        </div>
    {% endfor %}
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>

<footer class="bg-warning text-white p-3 fixed-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2023 David</p>
        </div>
        <div class="col-md-6">
          <ul class="list-inline text-md-end">
            <p>Published Date: Feb, 16, 2023
            <p>Author: David Da Lian</p>
          </ul>
        </div>
      </div>
    </div>
  </footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

polls/templates/polls/postcom.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Post Comment</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <div class="container">
      <a class="navbar-brand fw-semibold" href="{% url 'polls:comments'%}">
        <img src="https://previews.dropbox.com/p/thumb/AB2fKOVRrqQIAX3Ws7PwgOFgZUxqcvJARlrGssT7geSR_n9Q5IUNFmP-QBBqLejuyNMihp6jEuboA0GMhLQj1S6EJxHLPmdFFtqDEPwmrnhB0JrdvURhHlvkppkTOSCHbRHS44C7ANIW-6ogzmG4oiubIxjhUVGGmJtwfhRipAYdRJL9tJgQZaEfw9xrhzgqUdni_TdLmHrLZMwSuXDNsvy_HoAUVMcCYH8kQw2l9KOTuVelejFmWy8qzXl4_ijHjR4HRdx11P49yCIFUITV79nKrV5VQX7aSberR2xr-omSYZoORMe4tK27Ghjk0gl6bah6Hw6GKX4C2vT-YR6PJ3Cvakwgq_N_kV76gk8E3R6PIXQB6t1tCIYoU9U7aYpexOg/p.png" style="width: 50px; height:55px;" class="image-responsive me-3">
        MoFololo
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:index'%}">Polls</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:comments'%}">Comment</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:commentlist'%}">List</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<div class="container-sm bg-warning mx-5 my-5 p-3" style="border: 4px groove #eae30b; border-radius:5px ;">
  <h1 class="fw-bold"> Post a Comment</h1>
    <form class="m-2 p-2" style="border-radius:5px" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="title" class="form-label">Title:</label>
        <input type="text" class="form-control" id="title" placeholder="Some Title" name="title">
      </div>
      <div class="mb-3">
        <label for="text" class="form-label">Comment Text:</label>
        <textarea class="form-control" id="text" rows="3" placeholder="This class is..." name="text"></textarea>
      </div>
      <div class="d-flex justify-content-end pt-3 pb-2 px-5">
        <button class="btn btn-primary" type="submit">Submit</button>
      </div>  
    </form>
</div>

<footer class="bg-warning text-white p-3 fixed-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <p>&copy; 2023 David</p>
      </div>
      <div class="col-md-6">
        <ul class="list-inline text-md-end">
          <p>Published Date: Feb, 16, 2023
          <p>Author: David Da Lian</p>
        </ul>
      </div>
    </div>
  </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

</body>
</html>

polls/templates/polls/results.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
        <div class="container">
          <a class="navbar-brand fw-semibold" href="{% url 'polls:comments'%}">
            <img src="https://previews.dropbox.com/p/thumb/AB2fKOVRrqQIAX3Ws7PwgOFgZUxqcvJARlrGssT7geSR_n9Q5IUNFmP-QBBqLejuyNMihp6jEuboA0GMhLQj1S6EJxHLPmdFFtqDEPwmrnhB0JrdvURhHlvkppkTOSCHbRHS44C7ANIW-6ogzmG4oiubIxjhUVGGmJtwfhRipAYdRJL9tJgQZaEfw9xrhzgqUdni_TdLmHrLZMwSuXDNsvy_HoAUVMcCYH8kQw2l9KOTuVelejFmWy8qzXl4_ijHjR4HRdx11P49yCIFUITV79nKrV5VQX7aSberR2xr-omSYZoORMe4tK27Ghjk0gl6bah6Hw6GKX4C2vT-YR6PJ3Cvakwgq_N_kV76gk8E3R6PIXQB6t1tCIYoU9U7aYpexOg/p.png" style="width: 50px; height:55px;" class="image-responsive me-3">
            MoFololo
          </a>
    
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
            <span class="navbar-toggler-icon"></span>
          </button>
    
          <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:index'%}">Polls</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:comments'%}">Comment</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:commentlist'%}">List</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

<div class="container-fluid mx-3 my-5 p-3">
    <h1 class="fw-bold">Result for Question: "{{ question.question_text }}"</h1>
        {% for choice in question.choice_set.all %}
            <div class="border-start border-warning border-5 m-5 p-3">
                {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
            </div>
        {% endfor %}
    <div class="d-flex justify-content-end py-3 px-5">
        <a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">Vote Again</a>
    </div>
</div>

<footer class="bg-warning text-white p-3 fixed-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2023 David</p>
        </div>
        <div class="col-md-6">
          <ul class="list-inline text-md-end">
            <p>Published Date: Feb, 16, 2023
            <p>Author: David Da Lian</p>
          </ul>
        </div>
      </div>
    </div>
  </footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>